const fs = require("fs");
if (fs.existsSync("config.env"))
  require("dotenv").config({ path: "./config.env" });

function convertToBool(text, fault = "true") {
  return text === fault ? true : false;
}

module.exports = {
  SESSION_ID: process.env.SESSION_ID || "DAVE-AI:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEx1UXBOUjQ5SUtRcEZDbjRJSUkrcnR6dnFUc2ZxSitWMjVuK3oyVFNsRT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieFJVQnpjVUJrKy9QYWtCMHZsV1FZSFhjZ0Z3THNybmcrMGtCZUVyRDVrMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVQUhVR1NjWHZQUkc3UlIvTlQxV29xd1M5ejMwR3NIaGdTeUlROGVIU21nPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ6dkkxNFVXa1AzNnoxOUxmd2d4SGFBTkdtTkhTV0tiUHgwSkRtRkgzSlFNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IldFWTNRU1kxbXYzcGpuUHdxbnlQZ01oUGo1Nk9la21aS3VPcHA3U0gzRjg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhDTXkxK3FKVzNBdm1MbEt3K1phSDFIcmk4RWNSQXhKLzM2SFo0SXZaM0E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoid0FRVHpSeW1jT1RuckZETVBNWm8yT242YzZaV0xFM2loOSticExNQTgxZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUIwbVJ1N0xuTGIyTkVGT2VtRkhCZlcvQ2FLQ3JPS29ueElYMWVoUktTQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlEzUUZpQkN3dnRaTU1TRDh1TU9FT0JsNDhWVUdYaDA4YmpLMTM5elBlSDE2cXIyRWtwNnhVa2l6c0VZMVMrNVpnRjRlL0VST3krNHZsZjZPMHBTREJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTQ4LCJhZHZTZWNyZXRLZXkiOiJiOEwzTTlLL3VtVHJWWUJGV1ZsV21ObkNCWVRnKy91Z0NKcW50Y3Q3NnJvPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6ODEzLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6ODEzLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IkRBVkVCT1RTIiwibWUiOnsiaWQiOiIyMjYwNjUyNzI5Mzo0M0BzLndoYXRzYXBwLm5ldCIsImxpZCI6IjEyNDc5NTIwNzM0ODM4NDo0M0BsaWQiLCJuYW1lIjoi8J2RgPCdkLzwnZC+8J2QtPCdkLjwnZC/LUtNID4vPCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSk9Bak53Q0VQdWN0c2tHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiQTNDSzBmZGtneS9uK0ppeWs0ZnBDZ3lVRmpTR0ZFa2U3THgvbmVoMHBsRT0iLCJhY2NvdW50U2lnbmF0dXJlIjoibU9KblpQMkZ2SW94T1p0bWV5QVBmbFlhY2pjajlRT0xzUWtYN2tzcmJVbVk4UTJVR1doSlIxR0RveWJ2Y0Q2L1ZoNWk1L2UzcW9Ia2YwUzBQNitrQlE9PSIsImRldmljZVNpZ25hdHVyZSI6IlJhRDE3ZDczR09tQnVLTitpUjdxdCt6LzhJdm1KOWVUOVNxcnVkMExWMGVERDMzakhDQzkwNFpweE1xbTlVR0hOUjNrdzN3TUlJWExMUDg0ajNQZ0NRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjI2MDY1MjcyOTM6NDNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUU53aXRIM1pJTXY1L2lZc3BPSDZRb01sQlkwaGhSSkh1eThmNTNvZEtaUiJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUVnZ0YifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzY0NTkzMjg4LCJsYXN0UHJvcEhhc2giOiJubTNCYiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBTzBSIn0=",
  OWNER_NUM: process.env.OWNER_NUM || "22606527293",
  PREFIX: process.env.PREFIX || ".",
  AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
  AUTO_REACT_STATUS: process.env.AUTO_REACT_STATUS || "true",
  MODE : process.env.MODE || "public", 
  AUTO_STATUS_LIKE: process.env.AUTO_STATUS_LIKE || "true", 
  AUTO_RECORDING: convertToBool(process.env.AUTO_RECORDING || "false"), 
  ANTI_DELETE: convertToBool(process.env.ANTI_DELETE || "true"),
  AUTO_VOICE: process.env.AUTO_VOICE || "true",
  AUTO_CHAT_GF: process.env.AUTO_CHAT_GF || "true",
  AUTO_STICKER: process.env.AUTO_STICKER || "true",
  AUTO_REPLY: process.env.AUTO_REPLY || "true",
  OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
  ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/lekd2l.jpg",
  AUTO_REACT: convertToBool(process.env.AUTO_REACT || "true"),
  AUTO_REACT: process.env.AUTO_REACT === "true" ? true : false,
  CUSTOM_REACT_EMOJIS:
    process.env.CUSTOM_REACT_EMOJIS || "🥲,😂,😐,🙂,😔",

  // Add this line for your status view control:

};
